name: Dartlang Italia
description: Sito della community italiana dedicata al linguaggio Dart
url: http://www.dartlang-italia.it
source: .
destination: ./_site
markdown: kramdown
excerpt_separator: "<!--more-->"