name: Dartlang Italia
description: Sito della community italiana dedicata al linguaggio Dart
url: http://www.dartlang-italia.it
source: .
destination: ../build
markdown: kramdown
excerpt_separator: "<!--more-->"